require('./src/functions/exchangeToken')
require('./src/functions/kiteProxy')
require('./src/functions/test')
require('./src/functions/globalMarkets')
require('./src/functions/fiiDii')
require('./src/functions/emailAlert')
require('./src/functions/setToken')
require('./src/functions/news')
